version: "3.2"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes: 
      - /home/abed/project/Redis-Cache-Using-Spring-Boot/volume:/data
    
#  redis:
#     image: "redis:alpine"

#     command: redis-server --requirepass root

#     ports:
#      - "6379:6379"

#     volumes:
#      - /home/abed/project/Redis-Cache-Using-Spring-Boot/volume:/var/lib/redis
#      - /home/abed/project/Redis-Cache-Using-Spring-Boot/volume/redis.conf:/usr/local/etc/redis/redis.conf

#     environment:
#      - REDIS_REPLICATION_MODE=master

#     networks:
#       node_net:
#         ipv4_address: 172.28.1.4

# # networking for the Redis container
# networks:
#   node_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16