spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RedisCache?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: root